FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm install

COPY tsconfig*.json ./
COPY nest-cli.json ./

EXPOSE 3002 9229

CMD ["npm", "run", "start:dev"]
